compilers:
- compiler:
    spec: gcc@=7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        # Needed to use cargo for some reason (probably old openssl before certs=system)
        CARGO_HTTP_CAINFO: /etc/ssl/ca-bundle.pem
    extra_rpaths: []
- compiler:
    spec: nvhpc@23.7
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: oneapi@2023.2.1
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/icx
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/icpx
      f77: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/intel64/ifort
      fc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/intel64/ifort
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/compiler/lib/intel64
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - gcc/12.2.0
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        PE_ENV: GNU
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: cce@16.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - cce/16.0.1
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        PE_ENV: CRAY
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: cce@17.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - cce/17.0.1
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        PE_ENV: CRAY
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64:/glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/lib64
        LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/lib64
- compiler:
    spec: nvhpc@24.1
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: gcc@13.2.0
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gcc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/g++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gfortran
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: oneapi@2024.0.2
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/icx
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/icpx
      f77: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/ifx
      fc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: nvhpc@24.3
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.3/Linux_x86_64/24.3/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.3/Linux_x86_64/24.3/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.3/Linux_x86_64/24.3/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.3/Linux_x86_64/24.3/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.3/Linux_x86_64/24.3/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: nvhpc@24.7
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.7/Linux_x86_64/24.7/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.7/Linux_x86_64/24.7/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.7/Linux_x86_64/24.7/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.7/Linux_x86_64/24.7/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.7/Linux_x86_64/24.7/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/latest/bin/icx
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/latest/bin/icpx
      f77: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/latest/bin/ifx
      fc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.2.1/compiler/latest/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: nvhpc@24.9
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.9/Linux_x86_64/24.9/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.9/Linux_x86_64/24.9/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.9/Linux_x86_64/24.9/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.9/Linux_x86_64/24.9/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.9/Linux_x86_64/24.9/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
