compilers:
- compiler:
    spec: gcc@=7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@23.7
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/23.7/Linux_x86_64/23.7/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: oneapi@2023.2.1
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/icx
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/icpx
      f77: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/ifx
      fc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2023.2.1/compiler/latest/linux/compiler/lib/intel64
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - gcc/12.2.0
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        PE_ENV: GNU
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
