compilers:
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: sles15
    modules: []
    environment: {}
- compiler:
    spec: nvhpc@21.3
    paths:
      cc: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/21.3/Linux_x86_64/21.3/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/21.3/Linux_x86_64/21.3/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/21.3/Linux_x86_64/21.3/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/21.3/Linux_x86_64/21.3/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/21.3/Linux_x86_64/21.3/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: nvhpc@23.1
    paths:
      cc: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.1/Linux_x86_64/23.1/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.1/Linux_x86_64/23.1/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.1/Linux_x86_64/23.1/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.1/Linux_x86_64/23.1/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.1/Linux_x86_64/23.1/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: oneapi@2023.0.0
    paths:
      cc: /glade/u/apps/common/23.04/spack/opt/spack/intel-oneapi-compilers/2023.0.0/compiler/latest/linux/bin/icx
      cxx: /glade/u/apps/common/23.04/spack/opt/spack/intel-oneapi-compilers/2023.0.0/compiler/latest/linux/bin/icpx
      f77: /glade/u/apps/common/23.04/spack/opt/spack/intel-oneapi-compilers/2023.0.0/compiler/latest/linux/bin/intel64/ifort
      fc: /glade/u/apps/common/23.04/spack/opt/spack/intel-oneapi-compilers/2023.0.0/compiler/latest/linux/bin/intel64/ifort
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.04/spack/opt/spack/intel-oneapi-compilers/2023.0.0/compiler/latest/linux/compiler/lib/intel64
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: cce@15.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - cce/15.0.1
    environment:
      set:
        PE_ENV: CRAY
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: gcc@12.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - gcc/12.2.0
    environment:
      set:
        PE_ENV: GNU
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: nvhpc@23.5
    paths:
      cc: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.5/Linux_x86_64/23.5/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.5/Linux_x86_64/23.5/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.5/Linux_x86_64/23.5/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.5/Linux_x86_64/23.5/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.04/spack/opt/spack/nvhpc/23.5/Linux_x86_64/23.5/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
