toolchains:
  gcc-125:
  - spec: '%c=gcc@12.5.0'
    when: '%c'
  - spec: '%cxx=gcc@12.5.0'
    when: '%cxx'
  - spec: '%fortran=gcc@12.5.0'
    when: '%fortran'
  - spec: '%blas=openblas@0.3.30'
    when: '%blas'
  - spec: '%lapack=openblas@0.3.30'
    when: '%lapack'
  nvhpc-259:
  - spec: '%c=nvhpc@25.9'
    when: '%c'
  - spec: '%cxx=nvhpc@25.9'
    when: '%cxx'
  - spec: '%fortran=nvhpc@25.9'
    when: '%fortran'
  - spec: '%blas=nvhpc@25.9'
    when: '%blas'
  - spec: '%lapack=nvhpc@25.9'
    when: '%lapack'
  intel-2521:
  - spec: '%c=intel-oneapi-compilers@2025.2.1'
    when: '%c'
  - spec: '%cxx=intel-oneapi-compilers@2025.2.1'
    when: '%cxx'
  - spec: '%fortran=intel-oneapi-compilers@2025.2.1'
    when: '%fortran'
  - spec: '%blas=intel-oneapi-mkl@2025'
    when: '%blas'
  - spec: '%lapack=intel-oneapi-mkl@2025'
    when: '%lapack'
  cce-1900:
  - spec: '%c=cce@19.0.0'
    when: '%c'
  - spec: '%cxx=cce@19.0.0'
    when: '%cxx'
  - spec: '%fortran=cce@19.0.0'
    when: '%fortran'
  - spec: '%blas=cray-libsci@25.03.0'
    when: '%blas'
  - spec: '%lapack=cray-libsci@25.03.0'
    when: '%lapack'
  gcc-143:
  - spec: '%c=gcc@14.3.0'
    when: '%c'
  - spec: '%cxx=gcc@14.3.0'
    when: '%cxx'
  - spec: '%fortran=gcc@14.3.0'
    when: '%fortran'
  - spec: '%blas=openblas@0.3.30'
    when: '%blas'
  - spec: '%lapack=openblas@0.3.30'
    when: '%lapack'
